#!/bin/bash
# Quick Test für SelfAI Self-Improvement
# Startet SelfAI und gibt dir Test-Prompts

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║        🧪 SELFAI SELF-IMPROVEMENT QUICK TEST 🧪                ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Dieser Test führt dich durch die wichtigsten /selfimprove Szenarien."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 EMPFOHLENE TEST-REIHENFOLGE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  EINFACH (Dokumentation):"
echo "   /selfimprove Füge Docstrings zu allen Funktionen in custom_agent_loop.py hinzu"
echo ""
echo "2️⃣  MITTEL (Code-Qualität):"
echo "   /selfimprove Füge Error-Handling für Tool-Ausführungsfehler im Custom Agent Loop hinzu"
echo ""
echo "3️⃣  KOMPLEX (Features):"
echo "   /selfimprove Füge Token-Counting und Usage-Tracking zum Custom Agent Loop hinzu"
echo ""
echo "4️⃣  META (Selbst-Verbesserung):"
echo "   /selfimprove Verbessere die Self-Improvement Engine - mache sie besser"
echo ""
echo "5️⃣  ULTIMATE (Autonome Rekursion):"
echo "   /selfimprove Analysiere dich selbst und finde die beste Verbesserung"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🛡️  SICHERHEITS-INFO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ SICHER zu ändern:"
echo "   • selfai/tools/*.py (Tool-Implementierungen)"
echo "   • selfai/core/custom_agent_loop.py (Deine Implementierung!)"
echo "   • test_*.py (Test-Dateien)"
echo "   • *.md (Dokumentation)"
echo ""
echo "⚠️  GESCHÜTZT (werden NICHT geändert):"
echo "   • selfai/selfai.py (Haupt-Orchestrierung)"
echo "   • config_loader.py (Config-Management)"
echo "   • selfai/core/model_interface.py (Kritische Interfaces)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Drücke ENTER um SelfAI zu starten..."
read

echo ""
echo "🚀 Starte SelfAI..."
echo ""

python selfai/selfai.py
